services:
  mysql:
    image: mysql:8.4
    container_name: astral-mysql
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=astralteam
      - MYSQL_USER=astralteam
      - MYSQL_PASSWORD=astralteam
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
  
  valkey:
    image: valkey/valkey:9
    container_name: astral-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - valkey_data:/data

volumes:
  mysql_data: 
  valkey_data: 